### ISSUE TITLE
protein sequence being passed inside a list to the language model resulting in empty tokenization

### ISSUE THREAD

**Issue by YoelShoshan** [PaccMann/paccmann_gp#3]
In https://github.com/PaccMann/paccmann_gp/blob/main/paccmann_gp/affinity_minimization.py#L50

[self.protein] is sent to the language model sequence_to_token_indexes(), which expects a string.
This results in the entirety of the protein being treated as a single token to encode, resulting in a basically empty tokenization for all protein cases.

fix suggestions:

1. self.protein should be used instead of [self.protein]
2. It's possible that a stricter type check will be useful in pytoda lib

**Comment by drugilsberg** [comment]
Thanks @YoelShoshan opening soon a PR with the fix as reported here: https://github.com/PaccMann/paccmann_kinase_binding_residues/blob/5c11b34934a9160201de5beb19e8a6117c0ffbb7/pkbr/generative.py#L109

**Comment by drugilsberg** [comment]
Closed in #5 .
